name: DigitalOcean Authentication
description: Logs into DigitalOcean Registry
inputs:
  DIGITALOCEAN_ACCESS_TOKEN:
    required: true
    description: "DigitalOcean API Token"

runs:
  using: "composite"
  steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to DigitalOcean Container Registry
      run: doctl registry login --expiry-seconds 600
      shell: bash
