name: Deploy Docker Image
description: Deploy Docker image to DigitalOcean Droplet
inputs:
  REGISTRY_URL:
    description: 'DigitalOcean Registry URL'
    required: true
  HOST:
    description: 'SSH HOST: DigitalOcean Droplet'
    required: true
  USERNAME:
    description: 'USERNAME: DigitalOcean Droplet'
    required: true
  SSHKEY:
    description: 'SSH Key'
    required: true
  PASSPHRASE:
    description: 'SSH Key Passphrase'
    required: false
  DIGITALOCEAN_ACCESS_TOKEN:
    required: true
    description: "DigitalOcean API Token"
  REPOSITORY:
    description: 'DigitalOcean Registry Repository'
    required: true
  TAG:
    description: 'DigitalOcean Registry Tag'
    required: true
  SERVER_DIR:
    description: 'Server Directory'
    required: true
  DOCKER_CONTAINER:
    description: 'Docker Container'
    required: true
    
runs:
  using: composite
  steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ inputs.HOST }}
        username: ${{ inputs.USERNAME }}
        key: ${{ inputs.SSHKEY }}
        passphrase: ${{ inputs.PASSPHRASE }}
        envs: GITHUB_SHA
        script: |
          # Login to DigitalOcean registry securely
          echo ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u "oauth" --password-stdin
          
          # Pull the latest image
          docker pull ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}

          # Restart container with the new image
          docker compose -f "${{ inputs.SERVER_DIR }}/docker-compose.yml" up -d --build "${{ inputs.DOCKER_CONTAINER }}"