name: Deploy Docker Image
description: Deploy Docker image to DigitalOcean Droplet
inputs:
  REPOSITORY:
    description: 'DigitalOcean Registry Repository'
    required: true
  TAG:
    description: 'DigitalOcean Registry Tag to pull'
    required: true
  SERVER_DIR:
    description: 'Server Directory of the Docker Compose file'
    required: true
  DOCKER_CONTAINER:
    description: 'Docker Container to restart'
    required: true
    
runs:
  using: composite
  steps:
    - name: Deploy to Digital Ocean droplet via SSH action
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        passphrase: ${{ secrets.PASSPHRASE }}
        envs: GITHUB_SHA
        script: |
          # Login to DigitalOcean registry securely
          echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u "oauth" --password-stdin
          
          # Pull the latest image
          docker compose pull ${{ secrets.DO_REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}

          # Restart container with the new image
          docker compose -f "${{ inputs.SERVER_DIR }}/docker-compose.yml" up -d --build "${{ inputs.DOCKER_CONTAINER }}"