name: B-P .NET Docker Image
description: Build and push .NET Docker image to DigitalOcean Registry
inputs:
  REGISTRY_URL:
    description: 'DigitalOcean Registry URL'
    required: true
  REPOSITORY:
    description: 'DigitalOcean Registry Repository'
    required: true
  TAG:
    description: 'DigitalOcean Registry Tag'
    required: true
  DIGITALOCEAN_ACCESS_TOKEN:
    description: "DigitalOcean Access token"
 
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY_URL }}
        username: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}
        password: ${{ inputs.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:{{ inpits.TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: user/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max