name: B-P .NET Docker Image
description: Build and push .NET Docker image to DigitalOcean Registry
inputs:
  REGISTRY_URL:
    description: 'DigitalOcean Registry URL'
    required: true
  REPOSITORY:
    description: 'DigitalOcean Registry Repository'
    required: true
  TAG:
    description: 'DigitalOcean Registry Tag'
    required: true
 
runs:
  using: composite
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build container image
      run: |
        SHORT_SHA=$(echo $GITHUB_SHA | head -c7)
        docker build -t ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA .
      shell: bash

    - name: Push image to DigitalOcean Container Registry
      run: |
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        SHORT_SHA=$(echo $GITHUB_SHA | head -c7)

        # Debugging - Check if image exists
        docker images | grep $SHORT_SHA || echo "Image not found!"

        docker tag ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}
        docker tag ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$SHORT_SHA ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$TIMESTAMP

        docker push ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:${{ inputs.TAG }}
        docker push ${{ inputs.REGISTRY_URL }}/${{ inputs.REPOSITORY }}:$TIMESTAMP
      shell: bash
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: user/app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max