name: Delete Docker Image
description: Delete Docker image from DigitalOcean Registry
inputs:
  DIGITALOCEAN_ACCESS_TOKEN:
    required: true
    description: "DigitalOcean API Token"
  DELETE_IMAGE_WITHOUT_TAG:
    required: true
    description: "Delete image without tag"
  SKIPPING_TAGS:
    required: true
    description: "Exclude tags"
  SKIPPING_IMAGES:
    required: true
    description: "Exclude recent images"
  DO_REPOSITORY:
    required: true
    description: "DigitalOcean Registry Repository"

runs:
  using: "composite"
  steps:
    - name: Delete old images in the registry
      run: |
          doctl registry repository list-tags bbv-backend --format Tag --no-header | grep -Ev "latest|develop" | tail -n +"3" | while read -r TAG; do
            echo "Deleting tag: $TAG"
            DIGEST=$(doctl registry repository list-manifests "$IMAGE_NAME" --format Digest,Tags --no-header | grep -w "$TAG" | awk '{print $1}')

            # Delete the tag
            doctl registry repository delete-tag "bbv-backend" "$TAG" --force

            # Delete the corresponding image if it has a digest
            if [[ -n "$DIGEST" ]]; then
                echo "Deleting image digest: $DIGEST"
                doctl registry repository delete-manifest "bbv-backend" "$DIGEST" --force
            else
                echo "No digest found for tag: $TAG (maybe it was shared with other tags)"
            fi
          done

      shell: bash

    - name: Delete images without tag
      shell: bash
      run: |
        doctl registry repository list-manifests bbv-backend --format Digest,Tags --no-header | awk '$2 == "" {print $1}' | while read -r DIGEST; do
            echo "Deleting untagged image: $DIGEST"
            doctl registry repository delete-manifest bbv-backend "$DIGEST" --force
        done
