name: Mirror All GitHub Repos to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:  # you run it manually, or add `schedule` for auto-sync

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sync Repo
        uses: actions/checkout@v3

      - name: Install GitHub CLI & jq
        run: |
          sudo apt update
          sudo apt install gh jq curl -y

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GHP }}" | gh auth login --with-token

      - name: Authenticate Azure DevOps API
        run: echo "${{ secrets.AZURE_PAT }}" > azure_token.txt

      - name: Get Repos and Mirror to Azure
        env:
          GITHUB_ORG: bbvgermany
          AZURE_ORG: ${{ secrets.ADO_ORG }}
          AZURE_PROJECT: ${{ secrets.ADO_PRO }}
          AZURE_PAT: ${{ secrets.ADO }}
          GITHUB_TOKEN: ${{ secrets.GHP }}
        run: |
          echo "📥 Fetching repositories from GitHub org $GITHUB_ORG..."
          gh repo list "$GITHUB_ORG" --limit 1000 --json name | jq -r '.[].name' > repos.txt

          while read REPO; do
            echo "🔄 Syncing $REPO..."

            # Check if repo exists in Azure
            RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" -u ":${AZURE_PAT}" \
              "https://dev.azure.com/$AZURE_ORG/$AZURE_PROJECT/_apis/git/repositories?searchText=$REPO&api-version=7.1-preview.1")

            # If repo doesn't exist (404), create it
            if [ "$RESPONSE" -eq 404 ]; then
              echo "Creating repository $REPO in Azure DevOps..."
              curl -X POST -u ":${AZURE_PAT}" \
                -H "Content-Type: application/json" \
                -d '{
                      "name": "'"$REPO"'",
                      "project": { "id": "'"$AZURE_PROJECT"'" }
                    }' \
                "https://dev.azure.com/$AZURE_ORG/_apis/git/repositories?api-version=7.1-preview.1"
            fi

            # Clone the repo from GitHub
            git clone --mirror "https://$GITHUB_TOKEN@github.com/$GITHUB_ORG/$REPO.git"
            cd "$REPO.git"

            # Add Azure remote
            git remote add azure "https://user:$AZURE_PAT@dev.azure.com/$AZURE_ORG/$AZURE_PROJECT/_git/$REPO"
            git push --mirror azure

            cd ..
            rm -rf "$REPO.git"
          done < repos.txt